# Generated by Django 4.1 on 2022-08-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objecttype",
            options={"verbose_name": "Тип", "verbose_name_plural": "Тип"},
        ),
        migrations.AddField(
            model_name="organisation",
            name="latitude",
            field=models.FloatField(
                default=0,
                help_text="Широта на которой находится объёект или организация.",
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="longitude",
            field=models.FloatField(
                default=0,
                help_text="Долгота на которой находится объёект или организация.",
                verbose_name="Долгота",
            ),
        ),
    ]
