# Generated by Django 4.1 on 2022-08-28 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_service", "0003_owner_alter_organisation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisation",
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.AlterModelOptions(
            name="owner",
            options={
                "verbose_name": "Подчинённость",
                "verbose_name_plural": "Подчинённость",
            },
        ),
        migrations.AlterField(
            model_name="owner",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Указатель на подчинённые объекты и организации.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner2organisation",
                to="api_service.organisation",
                verbose_name="Подчинённый",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Указатель на владельцев.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organisation2owner",
                to="api_service.organisation",
                verbose_name="Владелец",
            ),
        ),
    ]
